test: verify binary data received via D-Bus
The D-Bus test program and script now reads and verifies binary data.
Text and binary data are written to separate log files which must be
specified by the test script. The checksums of these log files will
be compared against the expected value.

Signed-off-by: Matheus Afonso Martins Moreira <matheus.a.m.moreira@gmail.com>

diff --git a/test/check_dbus.sh.in b/test/check_dbus.sh.in
--- a/test/check_dbus.sh.in
+++ b/test/check_dbus.sh.in
@@ -3,27 +3,36 @@
 DIR="@abs_top_srcdir@"
 BDIR="@abs_top_builddir@"
 LOG="/tmp/zbar_dbus_test_$$.log"
+LOG_BIN="/tmp/zbar_dbus_test_$$.bin"
 
-EXPECTED="7bfb83f7d54763ddb5841f0892e79071d4bb2c70"
+EXPECTED="7294377b69fb00c7e0811429ab7a42cc8cecfda0"
+EXPECTED_BIN="df896e459e47a7d392031a7d4962722a143e276b"
 
 
-$BDIR/test/test_dbus -c1 -t5 >$LOG &
+$BDIR/test/test_dbus -c2 -t5 --log=$LOG --bin-log=$LOG_BIN &
 PID=$!
 
-trap "rm -r $LOG" EXIT
+trap "rm -r $LOG $LOG_BIN" EXIT
 
 $BDIR/zbarimg/zbarimg $DIR/examples/code-128.png 2>/dev/null >/dev/null
+$BDIR/zbarimg/zbarimg -Sbinary $DIR/examples/qr-code-binary.png 2>/dev/null >/dev/null
 
 wait $PID
 
-if [ ! -s $LOG ]; then
+if [ ! -s $LOG ] || [ ! -s $LOG_BIN ]; then
 	echo "FAILED: nothing received via D-Bus"
     exit -2
 fi
 
 CK="`cat $LOG  |sha1sum |cut -d" " -f 1`"
 if [ "x$CK" != "x$EXPECTED" ]; then
-	echo "FAILED: $CK instead of $EXPECTED"
+    echo "FAILED: $CK instead of $EXPECTED"
+    exit -2
+fi
+
+CK_BIN="`cat $LOG_BIN  |sha1sum |cut -d" " -f 1`"
+if [ "x$CK_BIN" != "x$EXPECTED_BIN" ]; then
+    echo "FAILED: $CK_BIN instead of $EXPECTED_BIN"
     exit -2
 fi
 
